package system

import (
	"blog/global"
	"blog/model/system"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"os"
)

type AuthorityInit struct {
}

//@Param data body systemReq.Register true "用户名, 昵称, 密码, 角色ID"

// @Tags SysInit
// @Summary 系统注册
// @Produce  application/json
// @Router /test [get]
func (b *AuthorityInit) InitTable(c *gin.Context) {
	err := global.GM_DB.AutoMigrate(
		// 系统模块表
		//system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		//system.SysDictionary{},
		//system.SysOperationRecord{},
		//system.SysAutoCodeHistory{},
		//system.SysDictionaryDetail{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		//system.SysAuthorityBtn{},s
		//system.SysAutoCode{},
		//
		//// 示例模块表
		//example.ExaFile{},
		//example.ExaCustomer{},
		//example.ExaFileChunk{},
		//example.ExaFileUploadAndDownload{},
		// 自动化模块表
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		global.GM_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GM_LOG.Info("register table success")
}
