captcha:
    key-long: 6
    img-width: 240
    img-height: 80
cors:
    mode: ""
    whitelist: []
gin:
    prot: 9999
    run-mode: debug
    is-open-swager: true
jwt:
    signing-key: 685e0bd8-7eca-4525-a15f-0fb736bcbd38
    expires-time: 604800
    buffer-time: 86400
    issuer: mind
local:
    path: uploads/file
    store-path: uploads/file
mysql:
    path: 47.97.99.8
    port: "3307"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: blog
    username: blog
    password: KB8GXp4jTK7LWtLA
    name: ""
    dsn: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: error
    log-zap: false
mysqllist:
    - path: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      name: system
      dsn: root:mind123@tcp(127.0.0.1:3306)/blog?&parseTime=True&loc=Local
      max-idle-conns: 10
      max-open-conns: 100
      log-mode: error
      log-zap: false
    - path: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      name: system2
      dsn: douyin:GLCwYM87n3Ke65rd@tcp(47.97.99.8:3307)/douyin?&parseTime=True&loc=Local
      max-idle-conns: 10
      max-open-conns: 100
      log-mode: error
      log-zap: false
port: 9999
rabbitmq:
    user: admin
    pass: admin
    port: ""
redis:
    db: 0
    addr: 47.97.99.8:6379
    password: "douyintest123!"
system:
    env: ""
    addr: 0
    db-type: mysql
    oss-type: local
    use-multipoint: false
    use-redis: true
    iplimit-count: 15000
    iplimit-time: 3600
